image: Visual Studio 2017
services:
  - mssql2016
  - postgresql
branches:
  only:
  - master
before_build:
  - cmd: dotnet --version
  - cmd: dotnet tool install coveralls.net --global
build_script:
  - cmd: dotnet build
test_script:
  - cmd: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover PlainSql.Migrations.Tests/PlainSql.Migrations.Tests.csproj
  - ps: csmacnz.Coveralls --opencover -i C:\projects\plainsql-migrations\PlainSql.Migrations.Tests\coverage.opencover.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
deploy: off
